import {test,expect} from '@playwright/test';
import {standaloneOnly} from './standalone-helper.js';
const account='00000000-0000-0000-0000-000000000001';
async function backend(page,role,signupError){let site=null,revision=0,works=[],passwordUpdates=0;const calls=[];
 await page.route('https://*.supabase.co/**',async route=>{const request=route.request(),url=new URL(request.url()),path=url.pathname;calls.push(path);let body={};if(request.method()==='POST'&&request.postData())body=request.postDataJSON();const user={id:account,email:role+'@example.test',user_metadata:{full_name:'Participante'}};
 const token={access_token:'test-access-token',refresh_token:'test-refresh-token',expires_in:3600};
 if(path==='/rest/v1/cms_site')return route.fulfill({json:[{document:site,revision}]});
 if(path==='/auth/v1/token')return route.fulfill({json:token});
 if(path==='/auth/v1/recover')return route.fulfill({json:{}});
 if(path==='/auth/v1/verify')return route.fulfill({json:token});
 if(path==='/auth/v1/user'&&request.method()==='PUT'){passwordUpdates++;return route.fulfill({json:user});}
 if(path==='/auth/v1/user')return route.fulfill({json:user});
 if(path==='/auth/v1/signup'&&signupError)return route.fulfill({status:signupError.status,json:{code:signupError.code,msg:signupError.msg}});
 if(path==='/auth/v1/signup')return route.fulfill({json:{user}});
 if(path==='/auth/v1/logout')return route.fulfill({status:204});
 if(path==='/rest/v1/cms_admins')return route.fulfill({json:role==='visitor'?[]:[{user_id:account,owner:role==='owner',chef:role==='chef'}]});
 if(path==='/rest/v1/rpc/publish_site'){site=body.new_document;revision++;return route.fulfill({json:{revision,document:site}});}
 if(path==='/rest/v1/rpc/submit_work_with_visibility'){works.push({id:'00000000-0000-0000-0000-000000000020',author_id:account,title:body.work_title,kind:body.work_kind,summary:body.work_summary,body:body.work_body,reference_url:body.work_reference,attachment_paths:[],status:'received',feedback:'',visibility:body.work_visibility||'private',created_at:new Date().toISOString()});return route.fulfill({json:works[0].id});}
 if(path==='/rest/v1/rpc/public_works')return route.fulfill({json:works.filter(w=>w.visibility==='public').map(({feedback,status,author_id,...w})=>w)});
 if(path==='/rest/v1/rpc/set_work_visibility'){works.find(w=>w.id===body.work_id).visibility=body.work_visibility;return route.fulfill({status:204});}
 if(path==='/rest/v1/work_submissions')return route.fulfill({json:works});
 if(path==='/rest/v1/rpc/review_work'){const item=works.find(item=>item.id===body.work_id);Object.assign(item,{status:body.decision,feedback:body.message});return route.fulfill({status:204});}
 return route.fulfill({status:404,json:{message:'unexpected_test_request'}});
 });return {calls,get passwordUpdates(){return passwordUpdates;},get site(){return site;},get works(){return works;},addWork(){works.push({id:'00000000-0000-0000-0000-000000000020',title:'Investigación de maíz',kind:'research',summary:'Una propuesta sobre técnicas de fermentación.',body:'Resultados de investigación y posible desarrollo gastronómico en colaboración.',status:'received',feedback:'',attachment_paths:[],created_at:new Date().toISOString()});}};
}
async function login(page,role){await page.goto('/#cuenta');await page.getByLabel('Correo electrónico',{exact:true}).fill(role+'@example.test');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-1234');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page.getByRole('heading',{name:role==='visitor'?'Hola, Participante.':'Tu panel de control'})).toBeVisible();}
test.beforeEach(async({page},info)=>{if(info.project.metadata.standalone)await standaloneOnly(page);});
test('visitor sees research invitation and has no editing tools',async({page})=>{await backend(page,'visitor');await page.goto('/#comparte');await expect(page.getByRole('heading',{name:'Comparte tu trabajo',exact:true})).toBeVisible();await expect(page.locator('[data-edit-panel]:visible')).toHaveCount(0);await expect(page.getByRole('link',{name:'Crear cuenta',exact:true})).toBeVisible();await page.goto('/#admin');await expect(page.getByRole('heading',{name:'Iniciar sesión'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('admin edits with pencil, adds content to every section and publishes',async({page})=>{const api=await backend(page,'owner');await login(page,'owner');await page.getByRole('link',{name:'Vista previa',exact:true}).click();await page.getByRole('button',{name:'Editar portada',exact:true}).first().click();const editor=page.locator('#cms-editor');await editor.getByLabel('Título principal',{exact:true}).fill('Bienvenidos a nuestra cocina');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('heading',{name:'Bienvenidos a nuestra cocina'})).toBeVisible();expect(api.site).toBe(null);
 for(const label of ['Noticias','Recetario','Nuestro libro','Comparte tu trabajo']){await page.getByRole('link',{name:label,exact:true}).click();await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Texto',exact:true}).click();await editor.getByLabel('Título',{exact:true}).fill('Texto en '+label);await editor.getByLabel('Texto',{exact:true}).fill('Contenido editable de esta sección');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('heading',{name:'Texto en '+label})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Menú o sección',exact:true}).click();await editor.getByLabel('Título de la sección',{exact:true}).fill('Laboratorio gastronómico');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await page.getByRole('link',{name:'Laboratorio gastronómico',exact:true}).click();await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Carrusel',exact:true}).click();await editor.getByLabel('Título',{exact:true}).fill('Fotografías del laboratorio');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('region',{name:'Fotografías del laboratorio'})).toBeVisible();await expect(page.locator('[data-carousel-toggle]')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('#editor-tools').getByRole('button',{name:'Publicar',exact:true}).click();await expect(page.locator('#toast')).toHaveText('Cambios publicados para todos los visitantes.');expect(api.site.home.title).toBe('Bienvenidos a nuestra cocina');expect(api.site.sectionBlocks.comparte).toHaveLength(1);
 await page.getByRole('button',{name:'Cerrar sesión',exact:true}).first().click();await expect(page.locator('#editor-tools')).toBeHidden();await page.getByRole('link',{name:'Noticias',exact:true}).click();await expect(page.getByRole('heading',{name:'Bienvenidos a nuestra cocina'})).toBeVisible();});
test('participants submit work and can see its received status',async({page})=>{const api=await backend(page,'visitor');await login(page,'visitor');await page.getByRole('link',{name:'Comparte tu trabajo',exact:true}).click();await page.getByLabel('Título de tu trabajo',{exact:true}).fill('Fermentación gastronómica');await page.getByLabel('Resumen').fill('Investigación sobre fermentación de maíz y sabores mexicanos.');await page.getByLabel('Investigación, resultados y posible colaboración').fill('Resultados de investigación sobre nuevas técnicas para desarrollar propuestas gastronómicas con el chef Checo.');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enviar a revisión'}).click();await expect(page.locator('#my-works')).toContainText('Fermentación gastronómica');await expect(page.locator('#my-works')).toContainText('Recibida');await expect(page.locator('[data-work-review]')).toHaveCount(0);expect(api.works).toHaveLength(1);await page.goto('/#admin');await expect(page.getByRole('heading',{name:'Hola, Participante.'})).toBeVisible();});
test('Checo selects privately from the research panel',async({page})=>{const api=await backend(page,'chef');api.addWork();await login(page,'chef');await page.getByRole('button',{name:'Trabajos y colaboración',exact:true}).click();await page.getByRole('button',{name:'Consultar propuestas',exact:true}).click();await expect(page.locator('#review-works')).toContainText('Investigación de maíz');await page.getByLabel('Estado').selectOption('selected');await page.getByLabel('Respuesta para el participante').fill('Me gustaría explorar esta investigación contigo.');await page.getByRole('button',{name:'Guardar decisión de Checo'}).click();await expect(page.locator('#review-works')).toContainText('Seleccionada por Checo');expect(api.works[0].status).toBe('selected');});
test('owner can read work but cannot select it without chef assignment',async({page})=>{const api=await backend(page,'owner');api.addWork();await login(page,'owner');await page.getByRole('button',{name:'Trabajos y colaboración',exact:true}).click();await page.getByRole('button',{name:'Consultar propuestas',exact:true}).click();await expect(page.locator('#review-works')).toContainText('Investigación de maíz');await expect(page.locator('[data-work-review]')).toHaveCount(0);});

test('registration displays persistent confirmation and does not pretend to sign in',async({page})=>{await backend(page,'visitor');await page.goto('/#registro');await page.getByLabel('Nombre',{exact:true}).fill('Participante');await page.getByLabel('Correo electrónico',{exact:true}).fill('participante@example.test');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-1234');await page.getByRole('button',{name:'Registrarme',exact:true}).click();await expect(page.locator('.account-card .notice[role="status"]')).toContainText('participante@example.test');await expect(page.locator('.account-card')).toContainText('carpeta de spam');await expect(page.getByRole('heading',{name:'Iniciar sesión'})).toBeVisible();});
test('registration explains email restrictions and preserves the form on failure',async({page})=>{await backend(page,'visitor',{status:422,code:'email_address_not_authorized',msg:'Email address not authorized'});await page.goto('/#registro');await page.getByLabel('Nombre',{exact:true}).fill('Participante');await page.getByLabel('Correo electrónico',{exact:true}).fill('participante@example.test');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-1234');await page.getByRole('button',{name:'Registrarme',exact:true}).click();await expect(page.locator('.form-error')).toContainText('destinatario');await expect(page.getByLabel('Correo electrónico',{exact:true})).toHaveValue('participante@example.test');await expect(page.getByRole('heading',{name:'Crear cuenta'})).toBeVisible();});
test('a participant can publish a work and withdraw it from the public gallery',async({page})=>{const api=await backend(page,'visitor');await login(page,'visitor');await page.getByRole('link',{name:'Comparte tu trabajo',exact:true}).click();await page.getByLabel(/Pública · Todos/).check();await page.getByLabel('Título de tu trabajo',{exact:true}).fill('Maíz para compartir');await page.getByLabel('Resumen').fill('Investigación gastronómica de maíz para compartir con la comunidad.');await page.getByLabel('Investigación, resultados y posible colaboración').fill('Resultados completos de una investigación gastronómica que puede ayudar a desarrollar técnicas con el chef Checo.');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enviar a revisión'}).click();await expect(page.locator('#public-works')).toContainText('Maíz para compartir');expect(api.works[0].visibility).toBe('public');await page.locator('#my-works').getByRole('button',{name:'Hacer privada'}).click();await expect(page.locator('#public-works')).not.toContainText('Maíz para compartir');expect(api.works[0].visibility).toBe('private');});
test('admin edits title, adds a picture and chooses colors by hexadecimal code',async({page})=>{await backend(page,'owner');await login(page,'owner');await page.getByRole('button',{name:'Colores y temas'}).click();await page.getByRole('button',{name:'Editar paleta de colores'}).click();const drawer=page.locator('#cms-editor');await drawer.getByLabel('Código de Fondo de la app',{exact:true}).fill('#243141');await drawer.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.locator('body')).toHaveCSS('background-color','rgb(36, 49, 65)');await page.getByRole('link',{name:'Vista previa',exact:true}).click();await page.getByRole('button',{name:'Editar portada',exact:true}).first().click();await drawer.getByLabel('Título principal',{exact:true}).fill('Nuestra cocina, tus ideas');await drawer.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('heading',{name:'Nuestra cocina, tus ideas'})).toBeVisible();await page.getByRole('button',{name:'Editar todos los elementos'}).click();await expect(page.locator('[data-layout-edit]')).not.toHaveCount(0);await page.getByRole('button',{name:'Editar elemento: Nuestra cocina, tus ideas',exact:true}).click();const picture='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j8ioAAAAASUVORK5CYII=';await drawer.getByLabel('Imagen del elemento',{exact:true}).fill(picture);await drawer.locator('[name="color-enabled"]').check();await drawer.getByLabel('Código de Color del texto',{exact:true}).fill('#a8dac0');await drawer.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.locator('.hero h1 img')).toHaveAttribute('src',picture);await expect(page.locator('.hero h1')).toHaveCSS('color','rgb(168, 218, 192)');});
test('admin moves a component and returns it to its origin',async({page})=>{await backend(page,'owner');await login(page,'owner');await page.getByRole('link',{name:'Vista previa',exact:true}).click();await page.locator('[data-layout-key="home-welcome"]').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Mover elemento: Bienvenida',exact:true}).click();const modal=page.locator('#layout-move-dialog');const target=await modal.locator('option').evaluateAll(options=>options.find(o=>o.textContent==='Portada principal')?.value);expect(target).toBeTruthy();await modal.getByLabel('Colocar antes de').selectOption(target);await modal.getByRole('button',{name:'Mover aquí',exact:true}).click();let order=await page.locator('main>[data-layout-key]').evaluateAll(items=>items.map(e=>e.dataset.layoutKey));expect(order.indexOf('home-welcome')).toBeLessThan(order.indexOf('home-hero'));await page.getByRole('button',{name:'Restaurar acomodo original'}).click();await expect(page.locator('#toast')).toHaveText('Se restauró la ubicación original.');order=await page.locator('main>[data-layout-key]').evaluateAll(items=>items.map(e=>e.dataset.layoutKey));expect(order.indexOf('home-hero')).toBeLessThan(order.indexOf('home-welcome'));});

test('admin creates a recipe menu, documents an investigation and filters its recipes',async({page})=>{const api=await backend(page,'owner');await login(page,'owner');await page.getByRole('button',{name:'Recetario',exact:true}).click();const editor=page.locator('#cms-editor');await page.getByRole('button',{name:'+ Crear menú del recetario',exact:true}).click();await editor.getByLabel('Nombre del menú',{exact:true}).fill('Aprovechamientos de prueba');await editor.getByLabel('Descripción del menú',{exact:true}).fill('Colección preparada para documentar procesos.');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await page.locator('.cms-row').filter({hasText:'Fideo seco con chicharrón de filete'}).getByRole('button',{name:'Editar',exact:true}).click();await editor.getByLabel('Aprovechamientos de prueba',{exact:true}).check();await editor.getByLabel('Aprovechamiento',{exact:true}).fill('Registro de prueba pendiente de revisión por el chef.');await editor.getByLabel('Técnica o desarrollo',{exact:true}).fill('Técnica documentada para la prueba del editor.');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await page.getByRole('link',{name:'Recetario',exact:true}).click();await page.getByRole('button',{name:/Aprovechamientos de prueba/}).click();await expect(page.locator('.dish-card')).toHaveCount(1);await expect(page.locator('.dish-card')).toContainText('Fideo seco');await page.getByRole('button',{name:'Ver ingredientes',exact:true}).click();await expect(page.locator('#detail-dialog')).toContainText('Registro de prueba pendiente');await page.getByRole('button',{name:'Cerrar detalle'}).click();await page.locator('#editor-tools').getByRole('button',{name:'Publicar',exact:true}).click();await expect(page.locator('#toast')).toHaveText('Cambios publicados para todos los visitantes.');expect(api.site.recipeMenus[0].name).toBe('Aprovechamientos de prueba');expect(api.site.recipes[0].menuIds).toEqual([api.site.recipeMenus[0].id]);});
test('admin transfers a block between sections and restores its original section',async({page})=>{await backend(page,'owner');await login(page,'owner');await page.getByRole('link',{name:'Recetario',exact:true}).click();await page.getByRole('button',{name:'+ Agregar',exact:true}).click();const editor=page.locator('#cms-editor');await editor.getByRole('button',{name:'Texto',exact:true}).click();await editor.getByLabel('Título',{exact:true}).fill('Proceso experimental');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await page.locator('.custom-block').getByRole('button',{name:'Editar bloque',exact:true}).click();await editor.getByLabel('Sección del bloque').selectOption('noticias');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('heading',{name:'Proceso experimental'})).toHaveCount(0);await page.getByRole('link',{name:'Noticias',exact:true}).click();await expect(page.getByRole('heading',{name:'Proceso experimental'})).toBeVisible();await page.locator('.custom-block').getByRole('button',{name:'Editar bloque',exact:true}).click();await editor.getByRole('button',{name:'Devolver a su sección original'}).click();await expect(page.getByRole('heading',{name:'Proceso experimental'})).toHaveCount(0);await page.getByRole('link',{name:'Recetario',exact:true}).click();await expect(page.getByRole('heading',{name:'Proceso experimental'})).toBeVisible();});

test('password recovery sends an explicit return URL and displays the next steps',async({page})=>{await backend(page,'visitor');await page.goto('/#recuperar');await page.getByLabel('Correo electrónico',{exact:true}).fill('PERSON@example.test');const request=page.waitForRequest(r=>new URL(r.url()).pathname==='/auth/v1/recover');await page.getByRole('button',{name:'Enviar enlace',exact:true}).click();const sent=await request;expect(sent.postDataJSON()).toEqual({email:'person@example.test'});expect(new URL(sent.url()).searchParams.get('redirect_to')).toBe('http://127.0.0.1:4173/?auth=recovery');await expect(page.locator('.account-card [role=status]')).toContainText('Solicitud enviada');await expect(page.locator('.recovery-steps')).toContainText('Escribe tu nueva contraseña dos veces');await expect(page.getByRole('button',{name:'Enviar otro enlace',exact:true})).toBeEnabled();await expect(page.getByLabel('Correo electrónico',{exact:true})).toHaveValue('person@example.test');});
test('password recovery callback without a type opens a verified reset form and saves a matching password',async({page})=>{const api=await backend(page,'visitor');await page.goto('/?auth=recovery#access_token=test-access-token&refresh_token=test-refresh-token&expires_in=3600');await expect(page.getByRole('heading',{name:'Nueva contraseña',exact:true})).toBeVisible();expect(new URL(page.url()).hash).toBe('#nueva-clave');expect(new URL(page.url()).search).toBe('');await expect(page.locator('.account-card')).toContainText('Enlace verificado');await page.getByLabel('Nueva contraseña',{exact:true}).fill('new-test-password-1234');await page.getByLabel('Confirmar nueva contraseña',{exact:true}).fill('different-test-password-1234');await page.getByRole('button',{name:'Guardar contraseña',exact:true}).click();await expect(page.locator('.form-error')).toContainText('no coinciden');expect(api.passwordUpdates).toBe(0);await page.getByLabel('Confirmar nueva contraseña',{exact:true}).fill('new-test-password-1234');await page.getByRole('button',{name:'Guardar contraseña',exact:true}).click();await expect(page.locator('.account-card [role=status]')).toContainText('Contraseña actualizada');expect(api.passwordUpdates).toBe(1);expect(new URL(page.url()).hash).toBe('#cuenta');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('password recovery links previously sent with a recovery type still work',async({page})=>{await backend(page,'visitor');await page.goto('/#access_token=test-access-token&refresh_token=test-refresh-token&type=recovery&expires_in=3600');await expect(page.getByRole('button',{name:'Guardar contraseña',exact:true})).toBeEnabled();expect(new URL(page.url()).hash).toBe('#nueva-clave');expect(page.url()).not.toContain('test-access-token');});
test('password recovery verifies a token hash from a custom email link and removes it from the URL',async({page})=>{await backend(page,'visitor');const verify=page.waitForRequest(r=>new URL(r.url()).pathname==='/auth/v1/verify');await page.goto('/?token_hash=test-token-hash&type=recovery');expect((await verify).postDataJSON()).toEqual({token_hash:'test-token-hash',type:'recovery'});await expect(page.getByRole('button',{name:'Guardar contraseña',exact:true})).toBeEnabled();expect(new URL(page.url()).search).toBe('');expect(new URL(page.url()).hash).toBe('#nueva-clave');});
test('expired password recovery link clears a previous account and offers a new link',async({page})=>{const api=await backend(page,'owner');await login(page,'owner');await page.goto('/?auth=recovery#error=access_denied&error_code=otp_expired&error_description=Expired');await expect(page.getByRole('heading',{name:'Recuperar acceso',exact:true})).toBeVisible();await expect(page.locator('.account-card [role=status]')).toContainText('caducó');await expect(page.getByRole('button',{name:'Enviar enlace',exact:true})).toBeEnabled();await expect(page.locator('#editor-tools')).toBeHidden();expect(page.url()).not.toContain('error=');expect(api.passwordUpdates).toBe(0);});
test('password reset without an authorized session explains how to get a new link',async({page})=>{const api=await backend(page,'visitor');await page.goto('/#nueva-clave');await expect(page.getByRole('link',{name:'Solicitar enlace nuevo',exact:true})).toBeVisible();await expect(page.locator('[data-account-form=reset]')).toHaveCount(0);await page.getByRole('link',{name:'Solicitar enlace nuevo',exact:true}).click();await expect(page.getByRole('button',{name:'Enviar enlace',exact:true})).toBeEnabled();expect(api.passwordUpdates).toBe(0);});
test('password recovery rejects invalid credentials before allowing a password change',async({page})=>{const api=await backend(page,'visitor');await page.route('https://*.supabase.co/auth/v1/user',route=>route.fulfill({status:401,json:{code:'bad_jwt',message:'invalid JWT'}}));await page.goto('/?auth=recovery#access_token=invalid-token&refresh_token=invalid-refresh&expires_in=3600');await expect(page.getByRole('heading',{name:'Recuperar acceso',exact:true})).toBeVisible();await expect(page.locator('.account-card [role=status]')).toContainText('ya no es válido');await expect(page.locator('[data-account-form=reset]')).toHaveCount(0);expect(api.passwordUpdates).toBe(0);expect(page.url()).not.toContain('invalid-token');});

test('admin adds a new plate from the recipe page, assigns its menu and publishes it',async({page})=>{const api=await backend(page,'owner');await login(page,'owner');await page.getByRole('link',{name:'Recetario',exact:true}).click();const before=await page.locator('.dish-card').count(),editor=page.locator('#cms-editor');await page.getByRole('button',{name:'+ Agregar platillo',exact:true}).click();await editor.getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('.dish-card')).toHaveCount(before);await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Menú del recetario',exact:true}).click();await editor.getByLabel('Nombre del menú',{exact:true}).fill('Menú de pruebas');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await page.getByRole('button',{name:/Menú de pruebas/}).click();await expect(page.locator('.dish-card')).toHaveCount(0);await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Platillo o receta',exact:true}).click();await expect(editor.getByLabel('Menú de pruebas',{exact:true})).toBeChecked();await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(editor.locator('.form-error')).toContainText('nombre');await editor.getByLabel('Nombre del plato',{exact:true}).fill('Platillo de prueba del editor');await editor.getByLabel('Categoría',{exact:true}).fill('Desarrollos');await editor.getByLabel('Ingredientes (uno por línea)',{exact:true}).fill('Ingrediente de prueba uno\nIngrediente de prueba dos');await editor.getByLabel('Preparación (un paso por línea)',{exact:true}).fill('Paso de prueba uno\nPaso de prueba dos');await editor.getByLabel('Aprovechamiento',{exact:true}).fill('Observación de prueba pendiente de revisión.');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.locator('.dish-card')).toHaveCount(1);await expect(page.locator('.dish-card')).toContainText('Platillo de prueba del editor');await page.locator('#editor-tools').getByRole('button',{name:'Publicar',exact:true}).click();await expect(page.locator('#toast')).toHaveText('Cambios publicados para todos los visitantes.');const item=api.site.recipes.find(recipe=>recipe.name==='Platillo de prueba del editor');expect(item.ingredients).toHaveLength(2);expect(item.steps).toHaveLength(2);expect(item.menuIds).toEqual([api.site.recipeMenus[0].id]);await page.getByRole('button',{name:'Cerrar sesión',exact:true}).first().click();await page.getByRole('link',{name:'Recetario',exact:true}).click();await expect(page.locator('.dish-card')).toContainText('Platillo de prueba del editor');});
