import {test,expect} from '@playwright/test';
import {standaloneOnly} from './standalone-helper.js';
const account='00000000-0000-0000-0000-000000000001';
async function backend(page,role){let site=null,revision=0,works=[];const calls=[];
 await page.route('https://*.supabase.co/**',async route=>{const request=route.request(),url=new URL(request.url()),path=url.pathname;calls.push(path);let body={};if(request.method()==='POST'&&request.postData())body=request.postDataJSON();const user={id:account,email:role+'@example.test',user_metadata:{full_name:'Participante'}};
 const token={access_token:'test-access-token',refresh_token:'test-refresh-token',expires_in:3600};
 if(path==='/rest/v1/cms_site')return route.fulfill({json:[{document:site,revision}]});
 if(path==='/auth/v1/token')return route.fulfill({json:token});
 if(path==='/auth/v1/user')return route.fulfill({json:user});
 if(path==='/auth/v1/signup')return route.fulfill({json:{user}});
 if(path==='/auth/v1/logout')return route.fulfill({status:204});
 if(path==='/rest/v1/cms_admins')return route.fulfill({json:role==='visitor'?[]:[{user_id:account,owner:role==='owner',chef:role==='chef'}]});
 if(path==='/rest/v1/rpc/publish_site'){site=body.new_document;revision++;return route.fulfill({json:{revision,document:site}});}
 if(path==='/rest/v1/rpc/submit_work'){works.push({id:'00000000-0000-0000-0000-000000000020',author_id:account,title:body.work_title,kind:body.work_kind,summary:body.work_summary,body:body.work_body,reference_url:body.work_reference,attachment_paths:[],status:'received',feedback:'',created_at:new Date().toISOString()});return route.fulfill({json:works[0].id});}
 if(path==='/rest/v1/work_submissions')return route.fulfill({json:works});
 if(path==='/rest/v1/rpc/review_work'){const item=works.find(item=>item.id===body.work_id);Object.assign(item,{status:body.decision,feedback:body.message});return route.fulfill({status:204});}
 return route.fulfill({status:404,json:{message:'unexpected_test_request'}});
 });return {calls,get site(){return site;},get works(){return works;},addWork(){works.push({id:'00000000-0000-0000-0000-000000000020',title:'Investigación de maíz',kind:'research',summary:'Una propuesta sobre técnicas de fermentación.',body:'Resultados de investigación y posible desarrollo gastronómico en colaboración.',status:'received',feedback:'',attachment_paths:[],created_at:new Date().toISOString()});}};
}
async function login(page,role){await page.goto('/#cuenta');await page.getByLabel('Correo electrónico',{exact:true}).fill(role+'@example.test');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-1234');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page.getByRole('heading',{name:role==='visitor'?'Hola, Participante.':'Tu panel de control'})).toBeVisible();}
test.beforeEach(async({page},info)=>{if(info.project.metadata.standalone)await standaloneOnly(page);});
test('visitor sees research invitation and has no editing tools',async({page})=>{await backend(page,'visitor');await page.goto('/#comparte');await expect(page.getByRole('heading',{name:'Comparte tu trabajo',exact:true})).toBeVisible();await expect(page.locator('[data-edit-panel]:visible')).toHaveCount(0);await expect(page.getByRole('link',{name:'Crear cuenta',exact:true})).toBeVisible();await page.goto('/#admin');await expect(page.getByRole('heading',{name:'Iniciar sesión'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('admin edits with pencil, adds content to every section and publishes',async({page})=>{const api=await backend(page,'owner');await login(page,'owner');await page.getByRole('link',{name:'Vista previa',exact:true}).click();await page.getByRole('button',{name:'Editar portada',exact:true}).first().click();const editor=page.locator('#cms-editor');await editor.getByLabel('Título principal',{exact:true}).fill('Bienvenidos a nuestra cocina');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('heading',{name:'Bienvenidos a nuestra cocina'})).toBeVisible();expect(api.site).toBe(null);
 for(const label of ['Noticias','Recetario','Nuestro libro','Comparte tu trabajo']){await page.getByRole('link',{name:label,exact:true}).click();await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Texto',exact:true}).click();await editor.getByLabel('Título',{exact:true}).fill('Texto en '+label);await editor.getByLabel('Texto',{exact:true}).fill('Contenido editable de esta sección');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('heading',{name:'Texto en '+label})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Menú o sección',exact:true}).click();await editor.getByLabel('Título de la sección',{exact:true}).fill('Laboratorio gastronómico');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await page.getByRole('link',{name:'Laboratorio gastronómico',exact:true}).click();await page.getByRole('button',{name:'+ Agregar',exact:true}).click();await editor.getByRole('button',{name:'Carrusel',exact:true}).click();await editor.getByLabel('Título',{exact:true}).fill('Fotografías del laboratorio');await editor.getByRole('button',{name:'Aplicar al borrador'}).click();await expect(page.getByRole('region',{name:'Fotografías del laboratorio'})).toBeVisible();await expect(page.locator('[data-carousel-toggle]')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('#editor-tools').getByRole('button',{name:'Publicar',exact:true}).click();await expect(page.locator('#toast')).toHaveText('Cambios publicados para todos los visitantes.');expect(api.site.home.title).toBe('Bienvenidos a nuestra cocina');expect(api.site.sectionBlocks.comparte).toHaveLength(1);
 await page.getByRole('button',{name:'Cerrar sesión',exact:true}).first().click();await expect(page.locator('#editor-tools')).toBeHidden();await page.getByRole('link',{name:'Noticias',exact:true}).click();await expect(page.getByRole('heading',{name:'Bienvenidos a nuestra cocina'})).toBeVisible();});
test('participants submit work and can see its received status',async({page})=>{const api=await backend(page,'visitor');await login(page,'visitor');await page.getByRole('link',{name:'Comparte tu trabajo',exact:true}).click();await page.getByLabel('Título de tu trabajo',{exact:true}).fill('Fermentación gastronómica');await page.getByLabel('Resumen').fill('Investigación sobre fermentación de maíz y sabores mexicanos.');await page.getByLabel('Investigación, resultados y posible colaboración').fill('Resultados de investigación sobre nuevas técnicas para desarrollar propuestas gastronómicas con el chef Checo.');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enviar a revisión'}).click();await expect(page.locator('#my-works')).toContainText('Fermentación gastronómica');await expect(page.locator('#my-works')).toContainText('Recibida');await expect(page.locator('[data-work-review]')).toHaveCount(0);expect(api.works).toHaveLength(1);await page.goto('/#admin');await expect(page.getByRole('heading',{name:'Hola, Participante.'})).toBeVisible();});
test('Checo selects privately from the research panel',async({page})=>{const api=await backend(page,'chef');api.addWork();await login(page,'chef');await page.getByRole('button',{name:'Trabajos y colaboración',exact:true}).click();await page.getByRole('button',{name:'Consultar propuestas',exact:true}).click();await expect(page.locator('#review-works')).toContainText('Investigación de maíz');await page.getByLabel('Estado').selectOption('selected');await page.getByLabel('Respuesta para el participante').fill('Me gustaría explorar esta investigación contigo.');await page.getByRole('button',{name:'Guardar decisión de Checo'}).click();await expect(page.locator('#review-works')).toContainText('Seleccionada por Checo');expect(api.works[0].status).toBe('selected');});
test('owner can read work but cannot select it without chef assignment',async({page})=>{const api=await backend(page,'owner');api.addWork();await login(page,'owner');await page.getByRole('button',{name:'Trabajos y colaboración',exact:true}).click();await page.getByRole('button',{name:'Consultar propuestas',exact:true}).click();await expect(page.locator('#review-works')).toContainText('Investigación de maíz');await expect(page.locator('[data-work-review]')).toHaveCount(0);});
