import { esc, linkAttributes } from './markup.js';
import { clone, validateSiteDocument, iconNames, sectionBlocks, createSiteDocument, imageURL } from './site-model.js';
const panels=[['overview','Resumen'],['appearance','Diseño e identidad'],['location','Ubicación y mapa'],['colors','Colores y temas'],['home','Portada y carrusel'],['news','Noticias'],['recipes','Recetario'],['menus','Menús y secciones'],['shortcuts','Accesos directos'],['book','Nuestro libro'],['works','Trabajos y colaboración'],['publish','Publicación y versiones'],['users','Usuarios y cuenta']];
const field=(path,label,type='text',options)=>({path,label,type,options});
const icons=iconNames.map(x=>[x,{none:'Sin icono',sparkles:'Destello',book:'Libro',utensils:'Cocina',news:'Noticias',heart:'Corazón',link:'Flecha',home:'Casa',image:'Imagen',mail:'Correo',pin:'Ubicación'}[x]]);
const verification=[['demo','Muestra'],['pending','Pendiente'],['verified','Confirmado']];
const schemas={
 colors:[field('appearance.background','Fondo de la app','color'),field('appearance.text','Color del texto','color'),field('appearance.accent','Botones y acentos','color'),field('appearance.muted','Texto secundario','color')],
 element:[field('color','Color del texto','optional-color'),field('backgroundColor','Color de fondo','optional-color'),field('borderColor','Color del borde','optional-color'),field('text','Texto o título','textarea'),field('image','Imagen del elemento','image'),field('alt','Descripción de la imagen'),field('link','Enlace'),field('icon','Icono','select',icons),field('align','Alineación','select',[['left','Izquierda'],['center','Centro'],['right','Derecha']]),field('size','Tamaño de texto (px)','number')],
 location:[field('location.title','Título del mapa'),field('location.address','Dirección'),field('location.query','Nombre o dirección para Google Maps'),field('location.buttonLabel','Texto del botón'),field('location.image','Fotografía de la ubicación','image')],
 workPage:[field('workPage.galleryImage','Imagen del laboratorio','image'),field('workPage.galleryEyebrow','Encabezado del laboratorio'),field('workPage.galleryDescription','Presentación del laboratorio','textarea'),field('workPage.image','Imagen de la sección','image'),field('workPage.galleryTitle','Título de trabajos públicos'),field('workPage.eyebrow','Encabezado'),field('workPage.title','Título'),field('workPage.description','Descripción','textarea'),field('workPage.invitation','Invitación a participar','textarea')],
 appearance:[field('restaurantName','Nombre del restaurante'),field('brand.logo','Logotipo','image'),field('brand.location','Ubicación'),field('brand.subtitle','Descripción corta'),field('brand.badge','Etiqueta de la cabecera'),field('brand.footer','Texto del pie'),field('appearance.background','Color de fondo','color'),field('appearance.text','Color del texto','color'),field('appearance.accent','Color de botones y acentos','color'),field('appearance.muted','Color de texto secundario','color'),field('appearance.font','Tipografía','select',[['Questrial','Questrial'],['system-ui','Sistema'],['Georgia','Georgia']]),field('appearance.width','Ancho máximo en escritorio (px)','number'),field('appearance.density','Espaciado','select',[['comfortable','Amplio'],['compact','Compacto']])],
 home:[field('home.labEyebrow','Encabezado del área de I+D'),field('home.labImage','Imagen del área de I+D','image'),field('home.labTitle','Título del área de I+D'),field('home.labDescription','Presentación del área de I+D','textarea'),field('home.labButtonLabel','Botón del área de I+D'),field('home.labButtonLink','Destino del área de I+D'),field('home.chefEyebrow','Encabezado del trabajo del chef'),field('home.chefTitle','Título del trabajo del chef'),field('home.chefDescription','Presentación del trabajo del chef','textarea'),field('home.chefImage','Imagen del chef','image'),field('home.chefImageAlt','Descripción de la imagen del chef'),field('home.chefButtonLabel','Botón del trabajo del chef'),field('home.chefButtonLink','Destino del trabajo del chef'),field('home.methodOneTitle','Primer enfoque'),field('home.methodOneText','Descripción del primer enfoque','textarea'),field('home.methodTwoTitle','Segundo enfoque'),field('home.methodTwoText','Descripción del segundo enfoque','textarea'),field('home.methodThreeTitle','Tercer enfoque'),field('home.methodThreeText','Descripción del tercer enfoque','textarea'),field('home.image','Imagen adicional','image'),field('home.eyebrow','Encabezado pequeño'),field('home.title','Título principal','textarea'),field('home.description','Descripción','textarea'),field('home.buttonLabel','Texto del botón'),field('home.buttonLink','Destino del botón'),field('home.buttonIcon','Icono del botón','select',icons),field('home.alignment','Alineación','select',[['center','Centrada'],['left','A la izquierda']]),field('home.interval','Segundos entre imágenes','seconds'),field('home.autoplay','Pasar imágenes automáticamente','checkbox'),field('home.welcomeTitle','Texto de bienvenida'),field('home.welcomeText','Descripción de bienvenida'),field('home.newsTitle','Título de historias'),field('home.newsEyebrow','Encabezado de historias'),field('home.newsSubtitle','Descripción de historias'),field('home.newsLayout','Acomodo de historias','select',[['carousel','Carrusel'],['grid','Cuadrícula'],['list','Lista']])],
 slides:[field('image','Fotografía','image'),field('alt','Descripción de la imagen'),field('focus','Encuadre','select',[['left','Izquierda'],['center','Centro'],['right','Derecha']])],
 news:[field('title','Título'),field('excerpt','Resumen','textarea'),field('body','Texto completo','textarea'),field('kind','Tipo de historia'),field('date','Fecha','date'),field('image','Fotografía','image'),field('icon','Icono','select',icons),field('buttonLabel','Texto del acceso al detalle'),field('verification','Estado del contenido','select',verification),field('source','Procedencia','textarea'),field('sourceURL','Enlace de la fuente')],
 recipeMenus:[field('name','Nombre del menú'),field('description','Descripción del menú','textarea'),field('image','Imagen del menú','image')],
 recipes:[field('menuIds','Menús de esta receta','recipe-menus'),field('research','Investigación y propósito','textarea'),field('technique','Técnica o desarrollo','textarea'),field('utilization','Aprovechamiento','textarea'),field('results','Resultados y observaciones','textarea'),field('name','Nombre del plato'),field('category','Categoría'),field('description','Descripción','textarea'),field('ingredients','Ingredientes (uno por línea)','lines'),field('steps','Preparación (un paso por línea)','lines'),field('servings','Porciones','optional-number'),field('complexity','Dificultad'),field('image','Fotografía','image'),field('art','Ilustración si no hay fotografía','select',[['generic','Plato neutro'],['fideo','Fideo'],['sope','Sope']]),field('icon','Icono','select',icons),field('buttonLabel','Texto del botón'),field('verification','Estado del contenido','select',verification),field('source','Procedencia','textarea'),field('sourceURL','Enlace de la fuente')],
 recipePage:[field('recipePage.image','Imagen de la sección','image'),field('recipePage.eyebrow','Encabezado'),field('recipePage.title','Título del recetario'),field('recipePage.description','Descripción','textarea'),field('recipePage.layout','Acomodo de platos','select',[['grid','Cuadrícula'],['list','Lista']])],
 navigation:[field('image','Imagen del acceso','image'),field('label','Nombre en la navegación'),field('icon','Icono','select',icons),field('visible','Mostrar en la navegación','checkbox')],
 pages:[field('image','Imagen de la sección','image'),field('title','Título de la sección'),field('eyebrow','Encabezado'),field('description','Descripción','textarea'),field('layout','Acomodo de bloques','select',[['grid','Cuadrícula'],['list','Lista']])],
 blocks:[field('title','Título'),field('text','Texto','textarea'),field('image','Imagen','image'),field('icon','Icono','select',icons),field('buttonLabel','Texto del botón'),field('link','Destino del botón'),field('slides','Imágenes del carrusel','image-list'),field('interval','Segundos entre imágenes','seconds'),field('autoplay','Pasar imágenes automáticamente','checkbox')],
 shortcuts:[field('image','Imagen del acceso','image'),field('label','Nombre del acceso'),field('link','Enlace o sección'),field('icon','Icono','select',icons)],
 book:[field('bookPage.readerIntro','Frase de bienvenida en el lector'),field('book.title','Nombre del libro'),field('bookPage.title','Título de la sección'),field('bookPage.description','Descripción corta'),field('bookPage.heading','Título del espacio del libro'),field('bookPage.body','Texto de bienvenida','textarea'),field('bookPage.buttonLabel','Texto del botón para cargar PDF'),field('bookPage.cover','Portada','image'),field('bookPage.pdfURL','PDF publicado','pdf')]
};
const get=(object,path)=>path.split('.').reduce((value,key)=>value?.[key],object);
const set=(object,path,value)=>{const parts=path.split('.');let current=object;for(const key of parts.slice(0,-1))current=current[key];current[parts.at(-1)]=value;};
const uid=prefix=>`${prefix}-${crypto.randomUUID().slice(0,12)}`;
function draftDB() {return new Promise((resolve,reject)=>{const r=indexedDB.open('balcon-cms-drafts',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function draftStorage(key,action,value) {
 const db=await draftDB();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('drafts',action==='get'?'readonly':'readwrite');const store=tx.objectStore('drafts');const request=action==='get'?store.get(key):action==='put'?store.put(value,key):store.delete(key);tx.oncomplete=()=>resolve(request.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}
}
export function createAdmin({service,initialSite,onPreview,onAccountChange,notify,work}) {
 let published=clone(initialSite),draft=clone(initialSite),revision=0,baseRevision=0,dirty=false,panel='overview',editorState=null,editorWorking=null,historyItems=[],adminItems=[],busy=false,connectionIssue='',accountNotice='';
 const drawer=document.createElement('dialog');drawer.id='cms-editor';drawer.className='cms-drawer';drawer.setAttribute('aria-labelledby','cms-editor-title');document.body.append(drawer);
 const confirm=document.createElement('dialog');confirm.id='cms-confirm';confirm.setAttribute('aria-labelledby','cms-confirm-title');document.body.append(confirm);
 let confirmAction;
 const draftKey=()=>`${service.config.url}:${service.user?.id}`;
 const announce=message=>notify(message);
 const preview=()=>{onPreview(clone(draft));onAccountChange();};
 const guard=()=>{if(!service.isAdmin){location.hash='#cuenta';throw new Error('Necesitas permisos de administrador.');}};
 async function remember(){try{await draftStorage(draftKey(),'put',{document:draft,baseRevision,dirty});}catch{announce('El borrador está en esta visita. Exporta una copia para conservarlo.');}}
 async function apply(next){guard();validateSiteDocument(next);draft=next;dirty=JSON.stringify(draft)!==JSON.stringify(published);await remember();preview();}
 async function restoreDraft(){if(!service.isAdmin)return;try{const saved=await draftStorage(draftKey(),'get');if(saved?.dirty){validateSiteDocument(saved.document);draft=saved.document;baseRevision=saved.baseRevision;dirty=true;}}catch{}preview();}
 function ask(title,body,action){confirmAction=action;confirm.innerHTML=`<h2 id="cms-confirm-title">${esc(title)}</h2><p>${esc(body)}</p><div class="actions"><button class="button secondary" data-cms-cancel>Cancelar</button><button class="button" data-cms-confirm>Continuar</button></div>`;confirm.showModal();}
 const loadingButton=async(button,action)=>{if(busy)return;busy=true;if(button)button.disabled=true;try{await action();}catch(error){announce(error.message || 'No pudimos completar la acción.');}finally{busy=false;if(button?.isConnected)button.disabled=false;}};
 function renderField(spec,object) {
  const value=get(object,spec.path),id=`cms-${spec.path.replaceAll('.','-')}`;
  let input;
  if(spec.type==='recipe-menus')return `<fieldset class="cms-field cms-menu-choices"><legend>${esc(spec.label)}</legend>${draft.recipeMenus.length?draft.recipeMenus.map(menu=>`<label><input type="checkbox" name="menuIds" value="${esc(menu.id)}" ${(value||[]).includes(menu.id)?'checked':''}>${esc(menu.name)}</label>`).join(''):'<p class="subtle">Primero crea un menú en el panel Recetario.</p>'}</fieldset>`;
  if(spec.type==='image-list')return `<fieldset class="cms-field"><legend>${esc(spec.label)}</legend>${(value||[]).map((slide,i)=>`<div class="cms-image-row"><label>Imagen ${i+1}<input name="${spec.path}.${i}.image" value="${esc(slide.image.startsWith('@')?'':slide.image)}" ${slide.image.startsWith('@')?`data-retain="${esc(slide.image)}" placeholder="Se conserva la imagen actual"`:''}></label><label>Descripción<input name="${spec.path}.${i}.alt" value="${esc(slide.alt)}"></label><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" data-cms-upload="${spec.path}.${i}.image" data-kind="image"><button type="button" class="button secondary" data-cms-slide-remove="${i}">Quitar imagen</button></div>`).join('')}<button type="button" class="button secondary" data-cms-slide-add>+ Añadir imagen</button></fieldset>`;
  if(['color','optional-color'].includes(spec.type)){const valid=/^#[a-f0-9]{6}$/i.test(value||'')?value:'#c7ac72';input=`${spec.type==='optional-color'?`<label class="checkbox-field"><input name="${spec.path}-enabled" type="checkbox" ${value?'checked':''}> Aplicar este color</label>`:''}<div class="color-picker-row"><input id="${id}" name="${spec.path}" type="color" value="${valid}" data-color-picker="${spec.path}"><input type="text" value="${valid}" data-color-code="${spec.path}" pattern="#[a-fA-F0-9]{6}" maxlength="7" aria-label="Código de ${esc(spec.label)}"></div>`;}
  else if(spec.type==='checkbox')input=`<input id="${id}" name="${spec.path}" type="checkbox" ${value?'checked':''}>`;
  else if(spec.type==='select')input=`<select id="${id}" name="${spec.path}">${spec.options.map(([key,label])=>`<option value="${key}" ${value===key?'selected':''}>${esc(label)}</option>`).join('')}</select>`;
  else if(['textarea','lines'].includes(spec.type))input=`<textarea id="${id}" name="${spec.path}" rows="${spec.type==='lines'?5:3}" maxlength="20000">${esc(Array.isArray(value)?value.join('\n'):value)}</textarea>`;
  else if(['image','pdf'].includes(spec.type)) {
   const original=spec.type==='image' && String(value).startsWith('@');
   input=`<input id="${id}" name="${spec.path}" type="text" value="${esc(original?'':value)}" placeholder="${original?'Se conserva la imagen actual':'URL HTTPS'}" ${original?`data-retain="${esc(value)}"`:''}><input type="file" data-cms-upload="${spec.path}" data-kind="${spec.type}" accept="${spec.type==='pdf'?'application/pdf,.pdf':'image/jpeg,image/png,image/webp,image/gif'}"><small>O carga ${spec.type==='pdf'?'un PDF de hasta 30 MB':'una imagen de hasta 6 MB'}. Este archivo será público.</small>`;
  } else input=`<input id="${id}" name="${spec.path}" type="${spec.type.includes('number') || spec.type==='seconds'?'number':spec.type}" ${spec.type==='seconds'?'min="2" max="20" step="1"':''} ${spec.type==='optional-number'?'min="1" max="10000"':''} value="${esc(spec.type==='seconds'?value/1000:value)}" maxlength="20000">`;
  return `<div class="cms-field ${spec.type==='checkbox'?'checkbox-field':''}"><label for="${id}">${esc(spec.label)}</label>${input}</div>`;
 }
 function findItem(type,id,document=draft){if(type==='slides')return document.home.slides.find(x=>x.id===id);if(type==='blocks')return [...Object.values(document.sectionBlocks || {}).flat(),...document.pages.flatMap(p=>p.blocks)].find(x=>x.id===id);return document[type]?.find(x=>x.id===id);}
 function fieldsFor(type,item){if(type!=='blocks')return schemas[type];const skip=new Set(item.type==='carousel'?['image']:['slides','interval','autoplay']);return schemas.blocks.filter(spec=>!skip.has(spec.path));}
 function readFields(form,item,type){
  const values=new FormData(form);
  for(const spec of fieldsFor(type,item)){
    let value=values.get(spec.path);
    if(spec.type==='recipe-menus')value=values.getAll('menuIds');
    else if(spec.type==='image-list')value=[...form.querySelectorAll(`[name^="${spec.path}."][name$=".image"]`)].map(input=>({image:input.value.trim()||input.dataset.retain||'',alt:form.elements.namedItem(input.name.replace('.image','.alt')).value.trim()}));
    else if(spec.type==='optional-color')value=values.has(spec.path+'-enabled')?String(value):'';
    else if(spec.type==='checkbox')value=values.has(spec.path);
    else if(spec.type==='lines')value=String(value).split('\n').map(x=>x.trim()).filter(Boolean);
    else if(['number','seconds','optional-number'].includes(spec.type))value=value===''&&spec.type==='optional-number'?null:Number(value)*(spec.type==='seconds'?1000:1);
    else {value=String(value||'').trim();const input=form.elements.namedItem(spec.path);if(!value&&input?.dataset.retain)value=input.dataset.retain;}
    if(['date','complexity','sourceURL'].includes(spec.path)&&value==='')value=null;
    set(item,spec.path,value);
  }
 }
 function openEditor(type,id='',working) {
  guard();const documentLevel=['appearance','home','book','recipePage','workPage','location','colors'].includes(type);
  const item=working || (documentLevel?draft:findItem(type,id));if(!item)return;editorWorking=clone(item);
  editorState={type,id,documentLevel};const labels={slides:'Imagen del carrusel',blocks:'Bloque de contenido',navigation:'Menú de navegación',recipePage:'Encabezado del recetario',pages:'Sección personalizada',recipeMenus:'Menú del recetario'};
  drawer.innerHTML=`<button class="close-button" data-cms-close aria-label="Cerrar editor">✕</button><span class="eyebrow">Editar borrador</span><h2 id="cms-editor-title">${esc(labels[type] || panels.find(x=>x[0]===type)?.[1] || type)}</h2><p class="subtle">Aplica los cambios y revísalos antes de publicarlos.</p><form data-cms-editor>${fieldsFor(type,item).map(spec=>renderField(spec,item)).join('')}${type==='blocks'?`<label class="cms-field">Sección del bloque<select name="blockDestination">${draft.navigation.map(nav=>`<option value="${esc(nav.id)}" ${blockSection(id)===nav.id?'selected':''}>${esc(nav.label)}</option>`).join('')}</select></label>${item.originSection?'<button class="button secondary" type="button" data-cms-block-origin>Devolver a su sección original</button>':''}`:''}<p class="form-error" role="alert" hidden></p><div class="drawer-actions"><button type="button" class="button secondary" data-cms-close>Cancelar</button><button class="button" type="submit">Aplicar al borrador</button></div></form>`;
  if(!drawer.open)drawer.showModal();
 }
 function listRows(type,items,titleKey) {
  return items.length?`<div class="cms-list">${items.map((item,i)=>`<div class="cms-row"><div><strong>${esc(item[titleKey] || item.alt || 'Sin título')}</strong>${type==='navigation'?`<small>${item.visible?'Visible':'Oculto'}</small>`:''}</div><div class="cms-row-actions"><button class="icon-button" data-cms-move="${type}" data-id="${item.id}" data-direction="-1" aria-label="Subir ${esc(item[titleKey]||item.alt)}" ${i===0?'disabled':''}>↑</button><button class="icon-button" data-cms-move="${type}" data-id="${item.id}" data-direction="1" aria-label="Bajar ${esc(item[titleKey]||item.alt)}" ${i===items.length-1?'disabled':''}>↓</button><button class="button secondary" data-edit-panel="${type}" data-edit-id="${item.id}">Editar</button>${type!=='navigation'?`<button class="icon-button" data-cms-delete="${type}" data-id="${item.id}" aria-label="Eliminar ${esc(item[titleKey]||item.alt)}">✕</button>`:''}</div></div>`).join('')}</div>`:'<p class="cms-empty">Todavía no hay elementos. Crea el primero.</p>';
 }
 const addButton=(type,label)=>`<button class="button" data-cms-add="${type}">+ ${label}</button>`;
 function body() {
  if(panel==='overview')return `<div class="admin-welcome"><span class="eyebrow">Todo en un lugar</span><h2>El laboratorio, a tu manera.</h2><p>Edita desde los paneles o toca un lápiz en la vista previa. Los visitantes ven la última versión publicada.</p><a class="button" href="#noticias">Abrir vista previa</a></div><div class="admin-stats">${[['news','Noticias',draft.news.length],['recipes','Recetario',draft.recipes.length],['menus','Menús',draft.navigation.length],['home','Imágenes',draft.home.slides.length]].map(([key,label,count])=>`<button data-admin-panel="${key}"><strong>${count}</strong><span>${label}</span></button>`).join('')}</div><p class="notice">${dirty?'Tienes cambios sin publicar.':'No hay cambios pendientes.'} El borrador se guarda en este navegador. Exporta una copia si quieres llevarlo a otro dispositivo.</p>`;
  if(panel==='colors')return `<p class="subtle">Elige un color visualmente o escribe su código hexadecimal. Para un elemento concreto usa Editar todos los elementos y toca su lápiz.</p><button class="button" data-edit-panel="colors">Editar paleta de colores</button><h3>Temas iniciales</h3><div class="theme-choices">${[['dark','Oscuro y dorado','#1c1c1b','#c7ac72'],['warm','Cálido','#34261f','#dfa866'],['light','Claro','#faf5ea','#8a6529']].map(([id,label,bg,accent])=>`<button class="button secondary" data-cms-theme="${id}"><span class="theme-swatch" style="background:${bg};border-color:${accent}"></span>${label}</button>`).join('')}</div>`;
  if(panel==='location')return `<p class="subtle">Actualiza la dirección, fotografía y el mapa al pie de la app.</p><button class="button" data-edit-panel="location">Editar ubicación</button>`;
  if(panel==='appearance')return `<p class="subtle">Identidad, colores, tipografía y espacios.</p><button class="button" data-edit-panel="appearance">Editar diseño e identidad</button>`;
  if(panel==='home')return `<div class="panel-actions"><button class="button secondary" data-edit-panel="home">Editar textos, botón y acomodo</button>${addButton('slides','Añadir imagen')}</div><h3>Imágenes del carrusel</h3>${listRows('slides',draft.home.slides,'alt')}<h3>Orden de la página de inicio</h3><div class="cms-list">${draft.home.sectionOrder.map((key,i)=>`<div class="cms-row"><strong>${{welcome:'Bienvenida',news:'Historias',shortcuts:'Accesos directos'}[key]}</strong><div class="cms-row-actions"><button class="icon-button" data-cms-section="${key}" data-direction="-1" ${i===0?'disabled':''} aria-label="Subir ${key}">↑</button><button class="icon-button" data-cms-section="${key}" data-direction="1" ${i===2?'disabled':''} aria-label="Bajar ${key}">↓</button></div></div>`).join('')}</div>`;
  if(panel==='news')return `${addButton('news','Crear noticia')}${listRows('news',draft.news,'title')}`;
  if(panel==='recipes')return `<p class="subtle">Edita recetas, ingredientes, preparación, fotografías, investigaciones, técnicas y aprovechamientos. Agrupa las fichas en menús propios.</p><div class="panel-actions">${addButton('recipes','Crear receta')}${addButton('recipeMenus','Crear menú del recetario')}<button class="button secondary" data-edit-panel="recipePage">Encabezado y acomodo</button></div><h3>Menús del recetario</h3>${listRows('recipeMenus',draft.recipeMenus,'name')}<h3>Recetas y aprovechamientos</h3>${listRows('recipes',draft.recipes,'name')}`;
  if(panel==='shortcuts')return `${addButton('shortcuts','Crear acceso directo')}<p class="subtle">Enlaza a una sección, sitio web, correo o teléfono.</p>${listRows('shortcuts',draft.shortcuts,'label')}`;
  if(panel==='menus')return `<p class="subtle">Cambia los nombres, iconos y el orden de la navegación. Crea secciones con sus propios bloques y botones.</p><h3>Navegación</h3>${listRows('navigation',draft.navigation,'label')}<div class="panel-actions">${addButton('pages','Crear menú o sección')}</div>${["noticias","recetario","libro","comparte"].map(id=>`<section class="cms-page"><h3>${esc(draft.navigation.find(item=>item.id===id)?.label || id)}</h3>${listRows("blocks",sectionBlocks(draft,id),"title")}<button class="button secondary" data-cms-add-menu="${id}">+ Agregar</button></section>`).join("")}${draft.pages.map(page=>`<section class="cms-page"><div class="cms-row"><strong>${esc(page.title)}</strong><div class="cms-row-actions"><button class="button secondary" data-edit-panel="pages" data-edit-id="${page.id}">Editar sección</button><button class="icon-button" data-cms-delete="pages" data-id="${page.id}" aria-label="Eliminar ${esc(page.title)}">✕</button></div></div>${listRows('blocks',page.blocks,'title')}<button class="button secondary" data-cms-add="blocks" data-page="${page.id}">+ Añadir bloque a ${esc(page.title)}</button></section>`).join('')}`;
  if(panel==='works')return work.panelMarkup();
  if(panel==='book')return `<div class="book-admin-note"><h3>El espacio de tu libro</h3><p>El libro sigue pendiente. Cuando lo tengas, podrás cambiar la portada, los textos y cargar el PDF para tus visitantes.</p><button class="button" data-edit-panel="book">Editar espacio del libro</button><p class="notice">El PDF que publiques será visible para todos. Los PDFs de prueba que el visitante carga en el lector siguen guardándose solo en su navegador.</p></div>`;
  if(panel==='publish')return `<p class="subtle">Versión publicada: ${revision}. ${dirty?'Hay cambios en tu borrador.':'El borrador coincide con lo publicado.'}</p><div class="panel-actions"><button class="button" data-cms-publish ${dirty?'':'disabled'}>Publicar cambios</button><button class="button secondary" data-cms-export>Exportar borrador</button><label class="button secondary">Importar borrador<input type="file" accept="application/json,.json" data-cms-import hidden></label><button class="button secondary" data-cms-reload>Cargar última publicación</button></div><p class="notice">Publicar reemplaza el contenido que ven todos los visitantes. Las versiones anteriores permiten preparar una restauración como borrador.</p><h3>Versiones anteriores</h3><button class="button secondary" data-cms-history>Consultar versiones</button><div id="cms-history">${historyItems.map(item=>`<div class="cms-row"><span>Versión ${item.revision} · ${esc(new Date(item.created_at).toLocaleDateString('es-MX'))}</span><button class="button secondary" data-cms-restore="${item.revision}">Usar como borrador</button></div>`).join('')}</div>`;
  return `<p>Cuenta: <strong>${esc(service.user?.email)}</strong></p><p class="subtle">${service.isOwner?'Propietario: puedes editar el sitio y gestionar administradores.':'Administrador: puedes editar y publicar el sitio.'}</p>${service.isOwner?`<h3>Cuenta del chef Checo</h3><p class="subtle">Asigna la cuenta confirmada que usará Checo. Solo esa cuenta puede seleccionar investigaciones; también tendrá acceso al editor.</p><form data-cms-chef><label class="cms-field">Correo de Checo<input name="email" type="email" required></label><button class="button">Asignar cuenta de Checo</button></form><h3>Administradores</h3><p class="subtle">La cuenta debe estar registrada y haber confirmado su correo.</p><form data-cms-grant><label class="cms-field">Correo de la cuenta<input name="email" type="email" required></label><button class="button">Dar acceso de administrador</button></form><button class="button secondary" data-cms-admins>Actualizar lista</button><div>${adminItems.map(item=>`<div class="cms-row"><span>${esc(item.email)} ${item.owner?'· Propietario':''} ${item.chef?'· Chef Checo':''}</span>${item.owner?'':`<button class="button secondary" data-cms-revoke="${esc(item.email)}">Retirar acceso</button>`}</div>`).join('')}</div>`:''}<button class="button secondary" data-account-logout>Cerrar sesión</button>`;
 }
 function adminMarkup() {
  if(!service.isAdmin)return accountMarkup('cuenta','Inicia sesión con una cuenta de administrador para editar.');
  return `<header class="admin-heading"><span class="eyebrow">Administración</span><h1>Tu panel de control</h1><p class="subtle">${esc(service.user.email)} · ${dirty?'Borrador sin publicar':'Todo actualizado'}</p></header><div class="admin-shell"><nav class="admin-nav" aria-label="Paneles de administración">${panels.map(([key,label])=>`<button data-admin-panel="${key}" ${panel===key?'aria-current="page"':''}>${label}</button>`).join('')}</nav><section class="admin-content"><div class="admin-panel-heading"><h2>${panels.find(x=>x[0]===panel)[1]}</h2></div>${body()}</section></div>`;
 }
 function accountMarkup(view='cuenta',message='') {
  const enabled=service.configured;message=message||accountNotice;
  if(view==='cuenta' && service.user)return `<section class="account-card"><span class="eyebrow">Mi cuenta</span><h1>Hola, ${esc(service.user.user_metadata?.full_name || 'bienvenido')}.</h1><p>${esc(service.user.email)}</p><p>${service.isAdmin?'Tu cuenta tiene acceso a la administración.':'Tu cuenta es de visitante. Los permisos de administración los asigna el propietario.'}</p>${service.roleIssue?`<p class="notice">${esc(service.roleIssue)}</p>`:''}${service.isAdmin?'<a class="button" href="#admin">Abrir panel de administración</a>':''}<a class="button secondary" href="#nueva-clave">Cambiar contraseña</a><button class="button secondary" data-account-logout>Cerrar sesión</button>${message?`<p class="notice" role="status">${esc(message)}</p>`:''}</section>`;
  const register=view==='registro',recover=view==='recuperar',reset=view==='nueva-clave';
  return `<section class="account-card"><span class="eyebrow">${esc(initialSite.restaurantName)}</span><h1>${register?'Crear cuenta':recover?'Recuperar acceso':reset?'Nueva contraseña':'Iniciar sesión'}</h1><p>${register?'Guarda tu acceso a la experiencia. Una cuenta nueva comienza como visitante.':recover?'Te enviaremos un enlace para recuperar tu cuenta.':reset?'Elige una contraseña nueva para tu cuenta.':'Entra para acceder a tu cuenta y, si tienes permisos, al editor.'}</p>${!enabled?'<p class="notice">El acceso por cuenta todavía no está activado.</p>':''}${connectionIssue?`<p class="notice">${esc(connectionIssue)}</p>`:''}${message?`<p class="notice" role="status">${esc(message)}</p>`:''}<form data-account-form="${register?'register':recover?'recover':reset?'reset':'login'}">${register?'<label class="cms-field">Nombre<input name="name" type="text" autocomplete="name" maxlength="100" required></label>':''}${!reset?'<label class="cms-field">Correo electrónico<input name="email" type="email" autocomplete="email" required></label>':''}${!recover?`<label class="cms-field">Contraseña<input name="password" type="password" autocomplete="${register||reset?'new-password':'current-password'}" minlength="${register||reset?'12':'1'}" maxlength="128" required></label>${register||reset?'<small>Usa al menos 12 caracteres.</small>':''}`:''}<p class="form-error" role="alert" hidden></p><button class="button" ${!enabled||reset&&!service.user?'disabled':''}>${register?'Registrarme':recover?'Enviar enlace':reset?'Guardar contraseña':'Entrar'}</button></form><div class="account-links"><a href="#cuenta">Iniciar sesión</a><a href="#registro">Registro</a><a href="#recuperar">Olvidé mi contraseña</a></div></section>`;
 }
 async function publish(button) {
  await loadingButton(button,async()=>{guard();await service.verify();guard();validateSiteDocument(draft);const result=await service.publish(draft,baseRevision);revision=result.revision;baseRevision=revision;published=clone(draft);dirty=false;await remember();preview();announce('Cambios publicados para todos los visitantes.');});
 }
 async function reload(){const latest=await service.published();if(latest.document){published=createSiteDocument(latest.document);validateSiteDocument(published);}revision=latest.revision;baseRevision=revision;draft=clone(published);dirty=false;await remember();preview();announce('Se cargó la última versión publicada.');}
 function arrayFor(type,document,id,pageId){if(type==='slides')return document.home.slides;if(type==='blocks'){const page=document.pages.find(p=>p.id===pageId||p.blocks.some(b=>b.id===id));if(page)return page.blocks;document.sectionBlocks ||= {noticias:[],recetario:[],libro:[]};if(pageId)return (document.sectionBlocks[pageId] ||= []);return Object.values(document.sectionBlocks).find(items=>items.some(b=>b.id===id));}return document[type];}
 function blockSection(id,document=draft){return document.pages.find(page=>page.blocks.some(block=>block.id===id))?.id || Object.entries(document.sectionBlocks||{}).find(([,items])=>items.some(block=>block.id===id))?.[0];}
 function transferBlock(document,id,destination,index){const source=blockSection(id,document);if(source===destination && index===undefined)return;const sourceItems=arrayFor('blocks',document,id),at=sourceItems?.findIndex(item=>item.id===id);if(at===undefined || at<0)throw new Error('No se encontró el bloque.');if(!document.navigation.some(nav=>nav.id===destination))throw new Error('La sección original ya no existe.');const item=sourceItems[at];item.originSection ||= source;item.originIndex ??= at;sourceItems.splice(at,1);const target=arrayFor('blocks',document,'',destination);target.splice(index===undefined?target.length:Math.min(index,target.length),0,item);}
 function openAdd(section){guard();drawer.innerHTML=`<button class="close-button" data-cms-close aria-label="Cerrar">✕</button><span class="eyebrow">Agregar a esta sección</span><h2 id="cms-editor-title">¿Qué quieres crear?</h2><div class="add-element-grid">${[['banner','Banner'],['carousel','Carrusel'],['image','Imagen'],['text','Texto'],['title','Título'],['button','Botón o enlace'],['shortcut','Acceso directo'],['menu','Menú o sección']].map(([key,label])=>`<button class="button secondary" data-new-element="${key}" data-section="${section}">${label}</button>`).join('')}</div>`;if(!drawer.open)drawer.showModal();} 
 document.addEventListener('click',event=>{
  const button=event.target.closest('button');if(!button || ![...button.attributes].some(a=>/^(data-cms-|data-admin-panel|data-edit-panel|data-account-logout|data-new-element)/.test(a.name)))return;
  if(button.hasAttribute('data-cms-publish')){void publish(button);return;}
  void loadingButton(null,async()=>{
   if(button.dataset.cmsTheme){guard();const next=clone(draft),themes={dark:{background:'#1c1c1b',text:'#f6f3ed',accent:'#c7ac72',muted:'#b6b4ac'},warm:{background:'#34261f',text:'#fff3e2',accent:'#dfa866',muted:'#d0bda6'},light:{background:'#faf5ea',text:'#2c2821',accent:'#8a6529',muted:'#625b4e'}};Object.assign(next.appearance,themes[button.dataset.cmsTheme]);await apply(next);announce('Tema aplicado al borrador.');return;}
   if(button.hasAttribute('data-cms-block-origin')){guard();const next=clone(draft),item=findItem('blocks',editorState.id,next);transferBlock(next,item.id,item.originSection,item.originIndex);delete item.originSection;delete item.originIndex;await apply(next);drawer.close();announce('El bloque volvió a su sección original.');return;}
   if(button.hasAttribute('data-cms-close')){drawer.close();return;}
   if(button.hasAttribute('data-cms-cancel')){confirm.close();return;}
   if(button.hasAttribute('data-cms-confirm')){const action=confirmAction;confirm.close();await action?.();return;}
   if(button.hasAttribute('data-account-logout')){try{await service.logout();}finally{draft=clone(published);dirty=false;onPreview(clone(published));onAccountChange();location.hash='#cuenta';}return;}
   if(button.dataset.adminPanel){guard();panel=button.dataset.adminPanel;if(!panels.some(x=>x[0]===panel))panel='overview';location.hash='#admin';onAccountChange();return;}
   if(button.dataset.editPanel){const type=button.dataset.editPanel;if(!schemas[type])return;if(!button.dataset.editId && ['news','recipes','shortcuts'].includes(type)){guard();panel=type;location.hash='#admin';onAccountChange();return;}openEditor(type,button.dataset.editId||'');return;}
   if(button.hasAttribute('data-cms-export')){guard();const url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='balcon-borrador.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
   if(button.hasAttribute('data-cms-reload')){guard();ask('Cargar última publicación','Se reemplazará tu borrador local. Exporta una copia si quieres conservarlo.',reload);return;}
   if(button.hasAttribute('data-cms-history')){guard();historyItems=await service.history();onAccountChange();return;}
   if(button.dataset.cmsRestore){guard();const item=historyItems.find(x=>x.revision===Number(button.dataset.cmsRestore));if(item)ask('Preparar restauración','La versión elegida se copiará al borrador. Después podrás revisarla y publicarla.',()=>apply(clone(item.document)));return;}
   if(button.hasAttribute('data-cms-admins')){guard();adminItems=await service.admins();onAccountChange();return;}
   if(button.dataset.cmsRevoke){guard();const email=button.dataset.cmsRevoke;ask('Retirar acceso de administrador',`La cuenta ${email} seguirá siendo visitante.`,async()=>{await service.setAdmin(email,false);adminItems=await service.admins();onAccountChange();});return;}
   if(button.hasAttribute('data-cms-add-menu')){openAdd(button.dataset.cmsAddMenu);return;}
   if(button.hasAttribute('data-cms-slide-add') || button.hasAttribute('data-cms-slide-remove')){guard();readFields(drawer.querySelector('form'),editorWorking,editorState.type);if(button.hasAttribute('data-cms-slide-add'))editorWorking.slides.push({image:'',alt:''});else editorWorking.slides.splice(Number(button.dataset.cmsSlideRemove),1);openEditor(editorState.type,editorState.id,editorWorking);return;}
   if(button.dataset.newElement){guard();const next=clone(draft),type=button.dataset.newElement;let item;
    if(type==='menu'){item={id:uid('section'),title:'Nueva sección',eyebrow:'',description:'',layout:'grid',blocks:[]};next.pages.push(item);next.navigation.push({id:item.id,label:item.title,icon:'none',visible:true});await apply(next);openEditor('pages',item.id);return;}
    item={id:uid('block'),type,title:{banner:'Nuevo banner',carousel:'Nuevo carrusel',image:'Nueva imagen',text:'Nuevo texto',title:'Nuevo título',button:'',shortcut:'Acceso directo'}[type],text:'',image:['banner','image'].includes(type)?'@table':'',icon:'none',buttonLabel:['button','shortcut'].includes(type)?'Abrir':'',link:'#noticias',slides:type==='carousel'?[{image:'@table',alt:'Mesa del chef'},{image:'@chef',alt:'El chef y la ciudad'}]:[],interval:3000,autoplay:true};
    arrayFor('blocks',next,'',button.dataset.section).push(item);await apply(next);openEditor('blocks',item.id);return;
   }
   if(button.dataset.cmsAdd){guard();const type=button.dataset.cmsAdd,next=clone(draft);let item;
    if(type==='slides')item={id:uid('slide'),image:'@table',alt:'Nueva imagen',focus:'center'};
    if(type==='news')item={id:uid('news'),title:'Nueva noticia',excerpt:'',body:'',kind:'Noticia',date:null,image:'@table',icon:'news',buttonLabel:'Leer más',verification:'pending',source:'Contenido proporcionado por el administrador.',sourceURL:null};
    if(type==='recipeMenus')item={id:uid('recipe-menu'),name:'Nuevo menú',description:'',image:''};
    if(type==='recipes')item={id:uid('recipe'),name:'Nueva receta',category:'Platos',description:'',ingredients:[],steps:[],complexity:null,servings:null,priceMXN:null,art:'generic',image:'',icon:'utensils',buttonLabel:'Ver ingredientes',verification:'pending',source:'Contenido proporcionado por el administrador.',sourceURL:null};
    if(type==='shortcuts')item={id:uid('shortcut'),label:'Nuevo acceso',link:'#noticias',icon:'link'};
    if(type==='pages'){item={id:uid('section'),title:'Nueva sección',eyebrow:'',description:'',layout:'grid',blocks:[]};next.navigation.push({id:item.id,label:item.title,icon:'none',visible:true});}
    if(type==='blocks')item={id:uid('block'),type:'text',title:'Nuevo bloque',text:'',image:'',icon:'none',buttonLabel:'',link:'#noticias'};
    if(!item)return;arrayFor(type,next,'',button.dataset.page).push(item);await apply(next);openEditor(type,item.id);return;
   }
   if(button.dataset.cmsDelete){guard();const type=button.dataset.cmsDelete,id=button.dataset.id;ask('Eliminar elemento','Se quitará del borrador. El cambio será público solo cuando publiques.',async()=>{const next=clone(draft),items=arrayFor(type,next,id);items.splice(items.findIndex(x=>x.id===id),1);if(type==='pages')next.navigation=next.navigation.filter(x=>x.id!==id);if(type==='recipeMenus')for(const recipe of next.recipes)recipe.menuIds=(recipe.menuIds||[]).filter(menuId=>menuId!==id);await apply(next);});return;}
   if(button.dataset.cmsMove || button.dataset.cmsSection){guard();const next=clone(draft),isSection=!!button.dataset.cmsSection,items=isSection?next.home.sectionOrder:arrayFor(button.dataset.cmsMove,next,button.dataset.id);const from=items.findIndex(x=>isSection?x===button.dataset.cmsSection:x.id===button.dataset.id),to=from+Number(button.dataset.direction);if(from>=0&&to>=0&&to<items.length){[items[from],items[to]]=[items[to],items[from]];await apply(next);}return;}
  });
 });
 document.addEventListener('submit',event=>{
  const form=event.target;if(!form.matches('[data-account-form],[data-cms-editor],[data-cms-grant],[data-cms-chef]'))return;event.preventDefault();
  const button=form.querySelector('button[type="submit"]')||form.querySelector('button:not([type="button"])');
  const error=form.querySelector('.form-error');if(error)error.hidden=true;
  void loadingButton(button,async()=>{
   try{
    const values=new FormData(form);
    if(form.dataset.accountForm){const action=form.dataset.accountForm;
      if(action==='login'){accountNotice='';await service.login(values.get('email'),values.get('password'));published=clone(published);draft=clone(published);baseRevision=revision;await restoreDraft();onAccountChange();location.hash=service.isAdmin?'#admin':'#cuenta';}
      if(action==='register'){accountNotice='';const signed=await service.register(values.get('name'),values.get('email'),values.get('password'));accountNotice=signed?'Cuenta creada.':`Solicitud de registro recibida para ${String(values.get('email')).trim()}. Revisa tu correo y la carpeta de spam y abre el enlace de confirmación antes de iniciar sesión. Si ya tienes una cuenta, puedes entrar o recuperar tu contraseña.`;onAccountChange();location.hash='#cuenta';announce(signed?'Cuenta creada.':'Revisa tu correo para confirmar el registro.');}
      if(action==='recover'){await service.recover(String(values.get('email')).trim().toLowerCase());accountNotice='Si el correo está registrado, recibirás un enlace para recuperar el acceso. Revisa también la carpeta de spam.';onAccountChange();announce(accountNotice);}
      if(action==='reset'){await service.changePassword(values.get('password'));location.hash='#cuenta';announce('Contraseña actualizada.');}
      form.reset();return;
    }
    guard();
    if(form.hasAttribute('data-cms-chef')){await service.setChef(values.get('email'));await service.verify();adminItems=await service.admins();onAccountChange();announce('Cuenta del chef Checo asignada.');return;}
    if(form.hasAttribute('data-cms-grant')){await service.setAdmin(values.get('email'),true);adminItems=await service.admins();onAccountChange();announce('Acceso de administrador actualizado.');return;}
    const next=clone(draft),state=editorState;if(state.type==='element'){const item=clone(editorWorking);readFields(form,item,'element');next.elementOverrides||={};next.elementOverrides[state.id]=item;await apply(next);drawer.close();announce('Elemento actualizado en el borrador.');return;}const item=state.documentLevel?next:findItem(state.type,state.id,next);
    const previousTitle=item.title;readFields(form,item,state.type);if(state.type==='blocks')transferBlock(next,item.id,values.get('blockDestination'));if(state.type==='pages'){const nav=next.navigation.find(x=>x.id===item.id);if(nav?.label===previousTitle)nav.label=item.title;}
    await apply(next);drawer.close();announce('Borrador actualizado. Revisa y publica cuando esté listo.');
   }catch(caught){if(error){error.textContent=caught.message;error.hidden=false;}else throw caught;}
  });
 });
 document.addEventListener('input',event=>{const input=event.target;if(input.matches('[data-color-picker]')){const code=drawer.querySelector(`[data-color-code="${input.dataset.colorPicker}"]`);if(code)code.value=input.value;}if(input.matches('[data-color-code]')&&/^#[a-f0-9]{6}$/i.test(input.value)){const picker=drawer.querySelector(`[data-color-picker="${input.dataset.colorCode}"]`);if(picker)picker.value=input.value;}});
 document.addEventListener('change',event=>{
  const input=event.target;if(input.matches('[data-cms-upload]'))void loadingButton(null,async()=>{guard();const file=input.files?.[0];if(!file)return;input.disabled=true;try{const url=await service.upload(file,input.dataset.kind);drawer.querySelector(`[name="${input.dataset.cmsUpload}"]`).value=url;announce('Archivo cargado. Aplica los cambios al borrador.');}finally{input.disabled=false;}});
  if(input.matches('[data-cms-import]'))void loadingButton(null,async()=>{guard();const file=input.files?.[0];if(!file)return;if(file.size>4000000)throw new Error('El archivo supera los 4 MB.');const value=JSON.parse(await file.text());validateSiteDocument(value);ask('Importar borrador','Se reemplazará tu borrador local. Los visitantes no verán cambios hasta que publiques.',()=>apply(value));input.value='';});
 });
 return {
  get isAdmin(){return service.isAdmin;},get dirty(){return dirty;},get configured(){return service.configured;},
  adminMarkup,accountMarkup,applyDocument:apply,
  editElement(key,defaults,tag,group){guard();const item={...defaults,...draft.elementOverrides?.[key]};for(const token of ['@table','@chef','@brand'])if(item.image===imageURL(token))item.image=token;openEditor('element',key,item);if(group)drawer.querySelector('[name="text"]').closest('.cms-field').hidden=true;},
  toolsMarkup(){return service.isAdmin?`<a href="#admin" class="button secondary">Panel de administración</a><span>${dirty?'Borrador sin publicar':'Edición de administrador'}</span><a href="#noticias" class="button secondary">Vista previa</a><button class="button secondary" data-layout-toggle aria-pressed="false">Editar todos los elementos</button><button class="button secondary" data-layout-reset-all>Restaurar acomodo original</button><button class="button" data-cms-publish ${dirty?'':'disabled'}>Publicar</button>`:'';},
  addMarkup(section){return service.isAdmin?`<div class="section-admin-toolbar"><span>Editar esta sección</span><button class="button" data-cms-add-menu="${section}">+ Agregar</button></div>`:'';},
  accountTools(){return service.user?`<a href="#${service.isAdmin?'admin':'cuenta'}">${service.isAdmin?'Administrar':'Mi cuenta'}</a><button data-account-logout>Cerrar sesión</button>`:'<a href="#cuenta">Iniciar sesión</a><a href="#registro">Registro</a>';},
  async initialize(){if(!service.configured)return;const results=await Promise.allSettled([service.published(),service.restore()]);if(results[0].status==='fulfilled'){const latest=results[0].value;if(latest.document){published=createSiteDocument(latest.document);validateSiteDocument(published);draft=clone(published);}revision=latest.revision;baseRevision=revision;}else connectionIssue='No pudimos actualizar el contenido. Puedes volver a intentarlo.';if(results[1].status==='rejected')connectionIssue='No pudimos recuperar tu sesión. Inicia sesión de nuevo.';onPreview(clone(published));await restoreDraft();},
  setPanel(value){if(panels.some(x=>x[0]===value))panel=value;}
 };
}
