import {esc} from './markup.js';
import {clone,safeHref,imageURL,iconMarkup} from './site-model.js';
const cross='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 2v20M2 12h20M8 6l4-4 4 4M8 18l4 4 4-4M6 8l-4 4 4 4M18 8l4 4-4 4" stroke="currentColor" stroke-width="1.5"/></svg>';
export function createLayout({getSite,getAdmin,notify}){
 let suppressClick=0;let nodes=new Map(),containers=new Map(),tab='',fullEditing=false,frame,drag;
 const layer=document.createElement('div');layer.id='layout-edit-layer';layer.setAttribute('aria-label','Herramientas de edición visual');document.body.append(layer);
 const moveDialog=document.createElement('dialog');moveDialog.id='layout-move-dialog';moveDialog.setAttribute('aria-labelledby','layout-move-title');document.body.append(moveDialog);
 function collect(currentTab){tab=currentTab;nodes=new Map();containers=new Map();
  const roots=[document.querySelector('.masthead'),document.querySelector('.navigation'),document.querySelector('main'),document.querySelector('#restaurant-location'),document.querySelector('.footer')];
  roots.forEach((root,r)=>{if(!root)return;const prefix=r===2?`page-${tab}`:['cabecera','navegacion','','ubicacion','pie'][r];
   const keyOf=el=>{if(el.dataset.editKey)return el.dataset.editKey;if(el.dataset.editContainer)return el.dataset.editContainer;if(el===root)return prefix;const parts=[];let node=el;while(node&&node!==root){const id=node.dataset.layoutKey||node.dataset.recipe||node.dataset.news||node.dataset.favorite||node.dataset.nav;if(id){parts.unshift(`${node.tagName.toLowerCase()}-${id}`);break;}parts.unshift(`${node.tagName.toLowerCase()}-${[...node.parentElement.children].filter(x=>x.tagName===node.tagName&&!x.classList.contains('layout-inline-tools')).indexOf(node)}`);node=node.parentElement;}return prefix+':'+parts.join('.');};
   [root,...root.querySelectorAll('*')].forEach(el=>{if(el.closest('#my-works,#public-works,#lab-count,[data-work-review],form,.reader-controls,.pdf-stage,#editor-tools,#brand-edit')||el.matches('.edit-pencil,.close-button')||el.closest('.carousel-controls'))return;const key=keyOf(el);el.dataset.editContainer=key;containers.set(key,el);if(el.matches('h1,h2,h3,p,img,a,button,.location-label,.pilot-label,.footer>span,[data-layout-key]')&&!el.closest('button,a')?.isSameNode(el.parentElement)&&!el.parentElement.closest('button,a')){el.dataset.editKey=key;nodes.set(key,el);}});
  });
 }
 function apply(){const changes=getSite().elementOverrides||{};for(const[key,value]of Object.entries(changes)){const el=nodes.get(key);if(!el)continue;
   if(value.text!==undefined&&el.tagName!=='IMG'&&!el.matches('[data-layout-key]'))el.textContent=value.text;
   if(el.tagName!=='IMG'&&value.image){const photo=document.createElement('img');photo.src=imageURL(value.image);photo.alt=value.alt||'';photo.className='element-added-image';el.append(photo);}
   if(el.tagName==='IMG'&&value.image){el.src=imageURL(value.image);el.alt=value.alt||'';}
   if(el.tagName==='A'&&value.link)el.href=safeHref(value.link);
   if(value.icon&&value.icon!=='none'&&el.tagName!=='IMG')el.insertAdjacentHTML('beforeend',iconMarkup(value.icon));
   for(const property of ['color','backgroundColor','borderColor'])if(/^#[a-f0-9]{6}$/i.test(value[property]||''))el.style[property]=value[property];
   if(value.align)el.style.textAlign=value.align;
   if(value.size)el.style.fontSize=`${value.size}px`;
   if(value.placement){const parent=containers.get(value.placement.container),before=nodes.get(value.placement.before);if(parent&&parent!==el&&!el.contains(parent)&&!parent.closest('button,a,form')&&(parent!==document.querySelector('.navigation')||el.tagName==='A')){if(parent&&(!before||before.parentElement===parent))parent.insertBefore(el,before||null);}}
  }
 }
 function paint(){if(drag)return;layer.innerHTML='';if(!getAdmin()?.isAdmin||['admin','cuenta','registro','recuperar','nueva-clave'].includes(tab))return;
  const entries=[...nodes].filter(([key,el])=>fullEditing||el.matches('[data-layout-key]')||el.matches('.footer>span'));
  for(const[key,el]of entries){const r=el.getBoundingClientRect();if(r.width<20||r.height<12||r.bottom<0||r.top>innerHeight||el.closest('[hidden]'))continue;const tool=document.createElement('div');tool.className='layout-float-tools';tool.style.left=`${Math.max(4,Math.min(innerWidth-100,r.right-96))}px`;tool.style.top=`${Math.max(2,r.top)}px`;const group=el.matches('[data-layout-key]');if(!fullEditing){tool.style.left=`${Math.max(4,Math.min(innerWidth-54,r.right-106))}px`;tool.innerHTML=`<button type="button" class="layout-cross" data-layout-move="${esc(key)}" aria-label="Mover elemento: ${esc(label(el))}">${cross}</button>`;layer.append(tool);continue;}tool.innerHTML=`<button type="button" class="layout-pencil" data-layout-edit="${esc(key)}" aria-label="Editar elemento: ${esc(label(el))}">✎</button><button type="button" class="layout-cross" data-layout-move="${esc(key)}" aria-label="Mover elemento: ${esc(label(el))}">${cross}</button>`;layer.append(tool);}
 }
 const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(paint);};
 function label(el){return(el.dataset.layoutLabel||el.getAttribute('aria-label')||el.getAttribute('alt')||el.textContent||'Imagen').trim().slice(0,65);}
 async function move(key,targetKey){const el=nodes.get(key),target=nodes.get(targetKey);if(!el||!target||el===target||el.contains(target)||target.parentElement.closest('form,button,a'))throw new Error('Elige otro elemento como destino.');const parent=target.parentElement;if(parent===document.querySelector('.navigation')&&el.tagName!=='A')throw new Error('La navegación admite accesos a secciones.');const next=clone(getSite());next.elementOverrides||={};next.elementOverrides[key]||={};next.elementOverrides[key].placement={container:parent.dataset.editContainer,before:targetKey};await getAdmin().applyDocument(next);notify('Ubicación cambiada en el borrador. Puedes devolverla a su origen.');}
 function openMove(key){const el=nodes.get(key);if(!el)return;const options=[...nodes].filter(([k,target])=>k!==key&&!el.contains(target)&&target.getBoundingClientRect().height>0&&!target.parentElement.closest('button,a,form')).map(([k,target])=>`<option value="${esc(k)}">${esc(label(target))}</option>`).join('');moveDialog.innerHTML=`<button class="close-button" data-layout-close aria-label="Cerrar">✕</button><h2 id="layout-move-title">Mover ${esc(label(el))}</h2><p>Arrastra la cruz sobre otro elemento o elige dónde colocarlo. El acomodo se adapta a cada pantalla.</p><form data-layout-position="${esc(key)}"><label class="cms-field">Colocar antes de<select name="target">${options}</select></label><button class="button">Mover aquí</button></form><button class="button secondary" data-layout-reset="${esc(key)}">Devolver a su origen</button>`;moveDialog.showModal();}
 layer.addEventListener('pointerdown',event=>{const button=event.target.closest('[data-layout-move]');if(!button)return;drag={key:button.dataset.layoutMove,x:event.clientX,y:event.clientY,moved:false};button.setPointerCapture(event.pointerId);});
 layer.addEventListener('pointermove',event=>{if(!drag)return;if(Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>10){drag.moved=true;if(event.clientY<64)window.scrollBy(0,-14);else if(event.clientY>innerHeight-64)window.scrollBy(0,14);layer.classList.add('is-dragging');document.body.classList.add('is-layout-dragging');}});
 layer.addEventListener('pointerup',event=>{if(!drag)return;const current=drag;drag=null;layer.classList.remove('is-dragging');document.body.classList.remove('is-layout-dragging');if(current.moved){suppressClick=Date.now()+400;layer.hidden=true;const destination=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-edit-key]');layer.hidden=false;if(destination)void move(current.key,destination.dataset.editKey).catch(error=>notify(error.message));else notify('Suelta sobre un elemento de la página.');}});
 layer.addEventListener('pointercancel',()=>{drag=null;layer.classList.remove('is-dragging');document.body.classList.remove('is-layout-dragging');});
 document.addEventListener('click',event=>{const button=event.target.closest('[data-layout-edit],[data-layout-move],[data-layout-reset],[data-layout-close],[data-layout-toggle],[data-layout-reset-all]');if(!button||!getAdmin()?.isAdmin||Date.now()<suppressClick)return;
  if(button.hasAttribute('data-layout-toggle')){fullEditing=!fullEditing;button.setAttribute('aria-pressed',String(fullEditing));button.textContent=fullEditing?'Cerrar edición de elementos':'Editar todos los elementos';schedule();return;}
  if(button.hasAttribute('data-layout-close')){moveDialog.close();return;}
  if(button.dataset.layoutEdit){const el=nodes.get(button.dataset.layoutEdit);if(!el)return;const pencil=el.querySelector('.edit-pencil');getAdmin().editElement(button.dataset.layoutEdit,{text:el.tagName==='IMG'||el.matches('[data-layout-key]')?'':el.textContent,link:el.tagName==='A'?el.getAttribute('href'):'',image:el.tagName==='IMG'?el.getAttribute('src'):'',alt:el.getAttribute('alt')||'',icon:'none',align:el.style.textAlign||'left',size:parseFloat(getComputedStyle(el).fontSize)||16},el.tagName,el.matches('[data-layout-key]'));return;}
  if(button.dataset.layoutMove){if(!document.body.classList.contains('is-layout-dragging'))openMove(button.dataset.layoutMove);return;}
  if(button.dataset.layoutReset||button.hasAttribute('data-layout-reset-all')){const next=clone(getSite());for(const[key,item]of Object.entries(next.elementOverrides||{}))if(button.hasAttribute('data-layout-reset-all')||key===button.dataset.layoutReset)delete item.placement;moveDialog.close();void getAdmin().applyDocument(next).then(()=>notify('Se restauró la ubicación original.'));}
 });
 moveDialog.addEventListener('submit',event=>{event.preventDefault();const form=event.target;void move(form.dataset.layoutPosition,new FormData(form).get('target')).then(()=>moveDialog.close()).catch(error=>notify(error.message));});
 window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);document.addEventListener('pointerup',schedule);
 return {mount(currentTab){collect(currentTab);apply();schedule();},refresh(){collect(tab);schedule();}};
}
