import { createSiteDocument, imageURL, safeHref, iconMarkup, pencilMarkup, sectionBlocks } from './site-model.js';
export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const lines = value => esc(value).replace(/\n/g,'<br>');
export function linkAttributes(value) { const url=safeHref(value);return `href="${esc(url)}"${url.startsWith('https:') ? ' target="_blank" rel="noopener noreferrer"' : ''}`; }
function carouselControls(label) {
  return `<div class="carousel-controls" data-carousel-controls hidden><button type="button" data-carousel-prev aria-label="Imagen anterior de ${label}"><svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m12 4-6 6 6 6" stroke="currentColor" stroke-width="1.5"/></svg></button><span class="carousel-counter" data-carousel-counter aria-live="off">1 / 2</span><button type="button" data-carousel-next aria-label="Imagen siguiente de ${label}"><svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m8 4 6 6-6 6" stroke="currentColor" stroke-width="1.5"/></svg></button></div>`;
}
export function newsMarkup(seed,{editing=false}={}) {
  const site=createSiteDocument(seed), h=site.home;
  const hero=`<section class="hero carousel editable-block align-${h.alignment}" data-carousel="carrusel de portada" data-interval="${h.interval}" data-autoplay="${h.autoplay}" data-layout-key="home-hero" data-layout-label="Portada principal" role="region" aria-roledescription="carrusel" aria-label="Fotografías de Balcón del Zócalo">${h.slides.map((slide,i)=>`<div class="hero-slide focus-${esc(slide.focus)}" data-carousel-slide ${i?'hidden':''}><img class="hero-photo" src="${esc(imageURL(slide.image))}" alt="${esc(slide.alt)}" width="1400" height="502" ${i?'':'fetchpriority="high"'}></div>`).join('')}<div class="hero-copy">${h.image?`<img class="intro-photo" src="${esc(imageURL(h.image))}" alt="">`:""}<span class="eyebrow">${esc(h.eyebrow)}</span><span class="hero-ornament" aria-hidden="true">✧</span><h1>${lines(h.title)}</h1><p>${lines(h.description)}</p>${h.buttonLabel?`<a class="button" ${linkAttributes(h.buttonLink)}>${esc(h.buttonLabel)} ${iconMarkup(h.buttonIcon,'arrow-icon')}</a>`:''}</div>${carouselControls('carrusel de portada')}<span class="photo-credit">Fotografías de ${esc(site.restaurantName)}</span>${editing?pencilMarkup('home'):''}</section>`;
  const welcome=`<section class="lab-home editable-block" data-layout-key="home-welcome" data-layout-label="Bienvenida" aria-label="Investigación y desarrollo y trabajo del chef Checo"><div class="lab-home-top"><span class="eyebrow">${esc(h.welcomeTitle)}</span><p>${esc(h.welcomeText)}</p></div><div class="lab-pathways"><article class="lab-pathway"><div class="lab-pathway-media lab-grid-media">${h.labImage?`<img src="${esc(imageURL(h.labImage))}" alt="Área de investigación y desarrollo" loading="lazy">`: '<div class="lab-emblem" aria-hidden="true"><span>I+D</span><small>COCINA EN EVOLUCIÓN</small></div>'}<span class="lab-media-caption">${esc(h.labEyebrow || 'Área de investigación y desarrollo')}</span></div><div class="lab-pathway-copy"><span class="eyebrow">${esc(h.labEyebrow || 'Área de investigación y desarrollo')}</span><h2>${esc(h.labTitle)}</h2><p>${esc(h.labDescription)}</p><a class="text-link" ${linkAttributes(h.labButtonLink || '#comparte')}>${esc(h.labButtonLabel || 'Explorar investigaciones')} ${iconMarkup('link')}</a></div></article><article class="lab-pathway"><div class="lab-pathway-media">${h.chefImage?`<img src="${esc(imageURL(h.chefImage))}" alt="${esc(h.chefImageAlt || 'Chef Checo en Balcón del Zócalo')}" loading="lazy">`:''}<span class="lab-media-caption">${esc(h.chefEyebrow || 'El trabajo del chef Checo')}</span></div><div class="lab-pathway-copy"><span class="eyebrow">${esc(h.chefEyebrow || 'El trabajo del chef Checo')}</span><h2>${esc(h.chefTitle)}</h2><p>${esc(h.chefDescription)}</p><a class="text-link" ${linkAttributes(h.chefButtonLink)}>${esc(h.chefButtonLabel)} ${iconMarkup('link')}</a></div></article></div><div class="lab-method" aria-label="Nuestra manera de explorar">${[['01',h.methodOneTitle,h.methodOneText],['02',h.methodTwoTitle,h.methodTwoText],['03',h.methodThreeTitle,h.methodThreeText]].map(([n,title,text])=>`<article><span class="lab-method-number" aria-hidden="true">${n}</span><h3>${esc(title)}</h3><p>${esc(text)}</p></article>`).join('')}</div>${editing?pencilMarkup('home'):''}</section>`;
  const news=`<section data-layout-key="home-news" data-layout-label="Noticias"><div class="section-heading editable-block"><div><span class="eyebrow">${esc(h.newsEyebrow)}</span><h2>${esc(h.newsTitle)}</h2></div><span class="subtle">${esc(h.newsSubtitle)}</span>${editing?pencilMarkup('news'):''}</div><section class="news-carousel carousel layout-${h.newsLayout}" ${h.newsLayout==='carousel'?`data-carousel="carrusel de historias" data-interval="${h.interval}" data-autoplay="${h.autoplay}" aria-roledescription="carrusel"`:''} role="region" aria-label="Guías del piloto"><div class="carousel-track">${site.news.map((item,i)=>`<article class="news-slide editable-block" data-layout-key="news-${esc(item.id)}" ${h.newsLayout==='carousel'?`data-carousel-slide ${i?'hidden':''}`:''}><button class="news-card" data-news="${esc(item.id)}"><div class="news-image"><img src="${esc(imageURL(item.image,'') || imageURL(i?'@table':'@chef'))}" alt="" width="900" height="600" loading="lazy"><span class="image-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span></div><div class="news-content"><div class="news-top"><span class="eyebrow">${iconMarkup(item.icon)} ${esc(item.kind)}</span>${item.verification==='demo'?'<span class="tag">Guía del piloto</span>':''}</div><h3>${esc(item.title)}</h3><p>${esc(item.excerpt)}</p><span class="text-link">${esc(item.buttonLabel || 'Leer más')} ${iconMarkup('link','arrow-icon')}</span></div></button>${editing?pencilMarkup('news',item.id):''}</article>`).join('')}</div>${h.newsLayout==='carousel'?carouselControls('carrusel de historias'):''}</section>${site.news.some(item=>item.verification==='demo')?'<p class="notice">Contenido de muestra. Las noticias oficiales se incorporarán después de verificarlas.</p>':''}</section>`;
  const shortcuts=site.shortcuts.length?`<section class="shortcut-grid editable-block" data-layout-key="home-shortcuts" aria-label="Accesos directos">${site.shortcuts.map(item=>`<a class="shortcut-card" data-shortcut="${esc(item.id)}" ${linkAttributes(item.link)}>${item.image?`<img class="shortcut-photo" src="${esc(imageURL(item.image))}" alt="">`:""}${iconMarkup(item.icon)}<span>${esc(item.label)}</span>${iconMarkup('link','arrow-icon')}</a>`).join('')}${editing?pencilMarkup('shortcuts'):''}</section>`:'';
  const sections={welcome,news,shortcuts}; return hero+h.sectionOrder.map(key=>sections[key]).join('');
}
export function blocksMarkup(blocks,{editing=false}={}) {
  return blocks.map(block=>{
    const type=block.type || 'text';
    const media=type==='carousel'?`<div class="block-carousel carousel" data-carousel="carrusel ${esc(block.id)}" data-interval="${Number(block.interval)||3000}" data-autoplay="${block.autoplay!==false}" role="region" aria-roledescription="carrusel" aria-label="${esc(block.title || 'Fotografías')}"><div class="block-carousel-track">${block.slides.map((slide,i)=>`<div data-carousel-slide ${i?'hidden':''}><img src="${esc(imageURL(slide.image))}" alt="${esc(slide.alt)}" loading="lazy"></div>`).join('')}</div>${carouselControls('carrusel '+esc(block.id))}</div>`:block.image?`<img class="block-image" src="${esc(imageURL(block.image))}" alt="${esc(block.title)}" loading="lazy">`:'';
    return `<article class="custom-block type-${type} editable-block" data-layout-key="block-${block.id}">${media}<div class="block-copy">${iconMarkup(block.icon)}${block.title?`<h2>${esc(block.title)}</h2>`:''}${block.text?`<p>${lines(block.text)}</p>`:''}${block.buttonLabel?`<a class="button secondary" ${linkAttributes(block.link)}>${esc(block.buttonLabel)} ${iconMarkup(block.icon || 'link','arrow-icon')}</a>`:''}</div>${editing?pencilMarkup('blocks',block.id):''}</article>`;
  }).join('');
}
export function customPageMarkup(page,{editing=false}={}) {
  return `<header class="intro editable-block" data-layout-key="custom-heading">${page.image?`<img class="intro-photo" src="${esc(imageURL(page.image))}" alt="">`:""}<span class="eyebrow">${esc(page.eyebrow)}</span><h1>${esc(page.title)}</h1><p>${esc(page.description)}</p>${editing?pencilMarkup('pages',page.id):''}</header><section class="custom-blocks layout-${page.layout==='list'?'list':'grid'}">${blocksMarkup(page.blocks,{editing})}</section>`;
}
export function extraBlocksMarkup(site,id,{editing=false}={}) {
  const blocks=sectionBlocks(site,id);return blocks.length?`<section class="custom-blocks layout-list" aria-label="Contenido de la sección">${blocksMarkup(blocks,{editing})}</section>`:'';
}
